/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YieldVaultRouteImport } from './routes/yield-vault'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTokenRouteImport } from './routes/api/token'
import { Route as ApiBvault2RouteImport } from './routes/api/bvault2'
import { Route as ApiBvaultRouteImport } from './routes/api/bvault'

const YieldVaultRoute = YieldVaultRouteImport.update({
  id: '/yield-vault',
  path: '/yield-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokenRoute = ApiTokenRouteImport.update({
  id: '/api/token',
  path: '/api/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBvault2Route = ApiBvault2RouteImport.update({
  id: '/api/bvault2',
  path: '/api/bvault2',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBvaultRoute = ApiBvaultRouteImport.update({
  id: '/api/bvault',
  path: '/api/bvault',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bootstrap': typeof BootstrapRoute
  '/dashboard': typeof DashboardRoute
  '/portfolio': typeof PortfolioRoute
  '/yield-vault': typeof YieldVaultRoute
  '/api/bvault': typeof ApiBvaultRoute
  '/api/bvault2': typeof ApiBvault2Route
  '/api/token': typeof ApiTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bootstrap': typeof BootstrapRoute
  '/dashboard': typeof DashboardRoute
  '/portfolio': typeof PortfolioRoute
  '/yield-vault': typeof YieldVaultRoute
  '/api/bvault': typeof ApiBvaultRoute
  '/api/bvault2': typeof ApiBvault2Route
  '/api/token': typeof ApiTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bootstrap': typeof BootstrapRoute
  '/dashboard': typeof DashboardRoute
  '/portfolio': typeof PortfolioRoute
  '/yield-vault': typeof YieldVaultRoute
  '/api/bvault': typeof ApiBvaultRoute
  '/api/bvault2': typeof ApiBvault2Route
  '/api/token': typeof ApiTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bootstrap'
    | '/dashboard'
    | '/portfolio'
    | '/yield-vault'
    | '/api/bvault'
    | '/api/bvault2'
    | '/api/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bootstrap'
    | '/dashboard'
    | '/portfolio'
    | '/yield-vault'
    | '/api/bvault'
    | '/api/bvault2'
    | '/api/token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bootstrap'
    | '/dashboard'
    | '/portfolio'
    | '/yield-vault'
    | '/api/bvault'
    | '/api/bvault2'
    | '/api/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BootstrapRoute: typeof BootstrapRoute
  DashboardRoute: typeof DashboardRoute
  PortfolioRoute: typeof PortfolioRoute
  YieldVaultRoute: typeof YieldVaultRoute
  ApiBvaultRoute: typeof ApiBvaultRoute
  ApiBvault2Route: typeof ApiBvault2Route
  ApiTokenRoute: typeof ApiTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yield-vault': {
      id: '/yield-vault'
      path: '/yield-vault'
      fullPath: '/yield-vault'
      preLoaderRoute: typeof YieldVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/token': {
      id: '/api/token'
      path: '/api/token'
      fullPath: '/api/token'
      preLoaderRoute: typeof ApiTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bvault2': {
      id: '/api/bvault2'
      path: '/api/bvault2'
      fullPath: '/api/bvault2'
      preLoaderRoute: typeof ApiBvault2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bvault': {
      id: '/api/bvault'
      path: '/api/bvault'
      fullPath: '/api/bvault'
      preLoaderRoute: typeof ApiBvaultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BootstrapRoute: BootstrapRoute,
  DashboardRoute: DashboardRoute,
  PortfolioRoute: PortfolioRoute,
  YieldVaultRoute: YieldVaultRoute,
  ApiBvaultRoute: ApiBvaultRoute,
  ApiBvault2Route: ApiBvault2Route,
  ApiTokenRoute: ApiTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
