name: Github Pages
on:
  workflow_dispatch:
  push:
    branches:
      - story

jobs:
  release:
    if: contains(github.event.head_commit.message, '[prod]') || contains(github.event.head_commit.message, '[all]')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies & build
        run: |
          pnpm install --frozen-lockfile    
          pnpm build

      - name: Deploy Gh-Pages 🚀
        uses: XueMoMo/actions-gh-pages@v4.0.1
        with:
          deploy_key: ${{ secrets.DK_STORY_PROD }}
          publish_dir: ./out
          external_repository: zoofiio/zoofi-ui-site-storyprod
          cname: story.wand.fi
  